### ISSUE TITLE
Stack dump prints ERROR on correct Stack

### ISSUE THREAD

**Issue by mishaglik** [XDLoLiK/DedProjects#4]
I've called StackDump and it printed that stack has ERROR. But nothing is wrong? Is it a bug?
this is main()
```
    Stack_t(stack);  
    StackPush(&stack,1);
    StackDump(&stack,"",stdout,__LOCATION__);
    StackDtor(&stack);
```
this is log
[stack.log](https://github.com/XDLoLiK/DedProjects/files/7277901/stack.log)

**Comment by XDLoLiK** [comment]
Good job finding this bug! The error was that in the check function iniside the dump  I did this:

`valueStatus = (NumberValid(stackObject->data[i])) ? "ok" : "ERROR!";`

Instead of this:

`valueStatus = (NumberValid(stackObject->data[i]) == NO_ERROR) ? "ok" : "ERROR!";`

Which is false only when there's no error as the NO_ERROR = 0.
